apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080       # Internal service port
      targetPort: 8080 # Container port (your app listens on this)
      nodePort: 31200  # Exposed EC2 port

